name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Push to Hugging Face Space
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      run: |
        git remote add hf https://GlobalBusinessAdvisors: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@huggingface.co/spaces/GlobalBusinessAdvisors/agentic-employment.git
        git push hf main --force
